# Generated by Django 5.2.5 on 2025-08-08 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('image_main', models.ImageField(blank=True, upload_to='product_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('maker', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='phone_devic_created_f45449_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceVariants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('capacity', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='phone.device')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('carrier', models.CharField(max_length=100)),
                ('category_1', models.CharField(help_text='e.g., 5G, LTE, 3G', max_length=100)),
                ('category_2', models.CharField(help_text='통신사 별 요금제 구분 (5GX, 0청년 등)', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.CharField(help_text='Data limit in MB', max_length=100)),
                ('calling', models.CharField(help_text='Call minutes limit', max_length=100)),
                ('sms', models.CharField(help_text='SMS limit', max_length=100)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='phone_plan_created_2d8090_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductDetailImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='phone.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('discount_type', models.CharField(choices=[('공시지원금', '공시지원금'), ('선택약정', '선택약정')], default=('공시지원금', '공시지원금'), max_length=50)),
                ('contract_type', models.CharField(choices=[('신규가입', '신규가입'), ('번호이동', '번호이동'), ('기기변경', '기기변경')], default=('기기변경', '기기변경'), max_length=50)),
                ('option_value', models.CharField(max_length=100)),
                ('device_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='phone.devicevariants')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='phone.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='best_price_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_price_option', to='phone.productoptions'),
        ),
        migrations.CreateModel(
            name='DeviceColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('color', models.CharField(max_length=50)),
                ('color_code', models.CharField(help_text='Hex color code, e.g., #FFFFFF', max_length=7)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='phone.device')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='phone_devic_created_1b8901_idx')],
            },
        ),
        migrations.CreateModel(
            name='DevicesImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='device_images/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='phone.device')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='phone_devic_created_704c72_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='devicevariants',
            index=models.Index(fields=['created_at'], name='phone_devic_created_dc652f_idx'),
        ),
        migrations.AddIndex(
            model_name='productdetailimages',
            index=models.Index(fields=['created_at'], name='phone_produ_created_c48c57_idx'),
        ),
        migrations.AddIndex(
            model_name='productoptions',
            index=models.Index(fields=['created_at'], name='phone_produ_created_5bbbd7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='phone_produ_created_bfb0e0_idx'),
        ),
    ]
