# Generated by Django 5.2.5 on 2025-08-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Brief description of the plan', max_length=255, null=True),
        ),
    ]
