# Generated by Django 5.2.5 on 2025-08-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='banner',
            name='phone_banne_created_a54bb2_idx',
        ),
        migrations.RemoveIndex(
            model_name='devicescolorimage',
            name='phone_devic_created_f91974_idx',
        ),
        migrations.RemoveIndex(
            model_name='productdetailimage',
            name='phone_produ_created_2cdd5d_idx',
        ),
        migrations.RemoveIndex(
            model_name='reviewimage',
            name='phone_revie_created_83037b_idx',
        ),
        migrations.AddField(
            model_name='productdetailimage',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
