# Generated by Django 5.2.5 on 2025-08-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_remove_banner_phone_banne_created_a54bb2_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='device_color',
        ),
        migrations.RemoveField(
            model_name='historicalorder',
            name='device_variant',
        ),
        migrations.RemoveField(
            model_name='order',
            name='device_color',
        ),
        migrations.RemoveField(
            model_name='order',
            name='device_variant',
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='storage_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='storage_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
