# Generated by Django 5.2.5 on 2025-08-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_plan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='series',
            field=models.CharField(blank=True, default='', help_text='e.g., 갤럭시 S, 아이폰, 갤럭시 Z', max_length=100),
        ),
    ]
