# Generated by Django 5.2.5 on 2025-08-12 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_remove_historicalorder_device_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='shipping_method',
            field=models.CharField(blank=True, default='우체국', help_text='배송 방법', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, default='우체국', help_text='배송 방법', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='phone.review'),
        ),
    ]
