# Generated by Django 5.2.5 on 2025-08-08 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_device_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicesColorImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='device_color_images/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('device_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='phone.devicecolors')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='DevicesImages',
        ),
        migrations.AddIndex(
            model_name='devicescolorimages',
            index=models.Index(fields=['created_at'], name='phone_devic_created_153c7a_idx'),
        ),
    ]
