# Generated by Django 5.2.5 on 2025-08-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0004_alter_historicalorder_shipping_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_mobile',
            field=models.ImageField(default='', upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_pc',
            field=models.ImageField(default='', upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
