# Generated by Django 5.2.5 on 2025-08-08 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0004_devicescolorimages_delete_devicesimages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoptions',
            name='option_value',
        ),
        migrations.AddField(
            model_name='productoptions',
            name='pio_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='추가 지원금', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productoptions',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='phone.plan'),
        ),
        migrations.AddField(
            model_name='productoptions',
            name='subsidy_amount_mnp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='전환지원금', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productoptions',
            name='subsidy_amount_standard',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='공시지원금', max_digits=10, null=True),
        ),
    ]
