# Generated by Django 5.2.5 on 2025-08-08 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0005_remove_productoptions_option_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoptions',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='phone.plan'),
        ),
    ]
