# Generated by Django 5.2.5 on 2025-08-13 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0005_banner_image_mobile_banner_image_pc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='password',
        ),
        migrations.RemoveField(
            model_name='order',
            name='password',
        ),
    ]
