# Generated by Django 5.2.5 on 2025-08-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0006_alter_productoptions_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoptions',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='최종 가격', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productoptions',
            name='pio_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='추가지원금', max_digits=10, null=True),
        ),
    ]
