# Generated by Django 5.2.5 on 2025-08-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0006_remove_historicalorder_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, help_text='Review image', null=True, upload_to='review_images/'),
        ),
        migrations.DeleteModel(
            name='ReviewImage',
        ),
    ]
