# Generated by Django 5.2.5 on 2025-08-08 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0007_productoptions_final_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceColors',
            new_name='DeviceColor',
        ),
        migrations.RenameModel(
            old_name='DevicesColorImages',
            new_name='DevicesColorImage',
        ),
        migrations.RenameModel(
            old_name='DeviceVariants',
            new_name='DeviceVariant',
        ),
        migrations.RenameModel(
            old_name='ProductDetailImages',
            new_name='ProductDetailImage',
        ),
        migrations.RenameModel(
            old_name='ProductOptions',
            new_name='ProductOption',
        ),
        migrations.RenameIndex(
            model_name='devicecolor',
            new_name='phone_devic_created_836f7d_idx',
            old_name='phone_devic_created_1b8901_idx',
        ),
        migrations.RenameIndex(
            model_name='devicescolorimage',
            new_name='phone_devic_created_f91974_idx',
            old_name='phone_devic_created_153c7a_idx',
        ),
        migrations.RenameIndex(
            model_name='devicevariant',
            new_name='phone_devic_created_1f7ab2_idx',
            old_name='phone_devic_created_dc652f_idx',
        ),
        migrations.RenameIndex(
            model_name='productdetailimage',
            new_name='phone_produ_created_2cdd5d_idx',
            old_name='phone_produ_created_c48c57_idx',
        ),
        migrations.RenameIndex(
            model_name='productoption',
            new_name='phone_produ_created_a79986_idx',
            old_name='phone_produ_created_5bbbd7_idx',
        ),
    ]
