# Generated by Django 5.2.5 on 2025-08-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0007_review_image_delete_reviewimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetailimage',
            name='type',
            field=models.CharField(choices=[('pc', 'pc'), ('mobile', 'mobile')], default='pc', max_length=25),
        ),
    ]
