# Generated by Django 5.2.5 on 2025-08-08 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0008_rename_devicecolors_devicecolor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='phone.device'),
        ),
    ]
