# Generated by Django 5.2.5 on 2025-08-08 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0009_product_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='phone.device'),
        ),
    ]
