# Generated by Django 5.2.5 on 2025-08-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0009_productoption_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoption',
            name='is_active',
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=False, help_text='활성화 여부'),
        ),
    ]
