# Generated by Django 5.2.5 on 2025-08-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0010_alter_product_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='final_price',
            field=models.IntegerField(blank=True, help_text='최종 가격', null=True),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='pio_discount',
            field=models.IntegerField(blank=True, help_text='추가지원금', null=True),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='subsidy_amount_mnp',
            field=models.IntegerField(blank=True, help_text='전환지원금', null=True),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='subsidy_amount_standard',
            field=models.IntegerField(blank=True, help_text='공시지원금', null=True),
        ),
    ]
