# Generated by Django 5.2.5 on 2025-08-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0010_remove_productoption_is_active_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Is the review public?'),
        ),
    ]
