# Generated by Django 5.2.5 on 2025-08-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0011_review_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Is the review public?'),
        ),
    ]
