# Generated by Django 5.2.5 on 2025-08-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0011_alter_productoption_final_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicevariant',
            name='price',
            field=models.IntegerField(default=0, help_text='Price in KRW'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.IntegerField(default=0, help_text='Price in KRW'),
        ),
    ]
