# Generated by Django 5.2.5 on 2025-08-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0012_alter_review_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='payment_period',
            field=models.CharField(choices=[('24개월', '24개월'), ('30개월', '30개월'), ('36개월', '36개월'), ('일시불', '일시불')], default='24개월', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_period',
            field=models.CharField(choices=[('24개월', '24개월'), ('30개월', '30개월'), ('36개월', '36개월'), ('일시불', '일시불')], default='24개월', max_length=50),
        ),
    ]
