# Generated by Django 5.2.5 on 2025-08-08 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0012_alter_devicevariant_price_alter_plan_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('discount_type', models.CharField(choices=[('공시지원금', '공시지원금'), ('선택약정', '선택약정')], default='공시지원금', max_length=50)),
                ('contract_type', models.CharField(choices=[('신규가입', '신규가입'), ('번호이동', '번호이동'), ('기기변경', '기기변경')], default='기기변경', max_length=50)),
                ('device_price', models.IntegerField(blank=True, help_text='기기 가격', null=True)),
                ('subsidy_amount_standard', models.IntegerField(blank=True, help_text='공시지원금', null=True)),
                ('subsidy_amount_mnp', models.IntegerField(blank=True, help_text='전환지원금', null=True)),
                ('pio_discount', models.IntegerField(blank=True, help_text='추가지원금', null=True)),
                ('final_price', models.IntegerField(blank=True, help_text='최종 가격', null=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone_1', models.CharField(max_length=15)),
                ('customer_phone_2', models.CharField(max_length=15)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_birth', models.DateField(blank=True, help_text='생년월일 (YYYY-MM-DD)', null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('address_1', models.CharField(blank=True, help_text='주소 1 (e.g., 도로명 주소)', max_length=255, null=True)),
                ('address_2', models.CharField(blank=True, help_text='주소 2 (e.g., 상세 주소)', max_length=255, null=True)),
                ('customer_memo', models.TextField(blank=True, help_text='고객 메모 (e.g., 배송 요청사항)', null=True)),
                ('admin_memo', models.TextField(blank=True, help_text='관리자 메모 (e.g., 주문 처리 관련 메모)', null=True)),
                ('status', models.CharField(choices=[('주문접수', '주문접수'), ('해피콜진행중', '해피콜진행중'), ('해피콜완료', '해피콜완료'), ('신용조회중', '신용조회중'), ('배송요청', '배송요청'), ('배송중', '배송중'), ('배송완료', '배송완료'), ('개통대기', '개통대기'), ('개통완료', '개통완료'), ('취소요청', '취소요청'), ('취소완료', '취소완료')], default='주문접수', max_length=50)),
                ('device_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='phone.devicecolor')),
                ('device_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='phone.devicevariant')),
                ('plan', models.ForeignKey(help_text='요금제 (e.g., 5G 요금제)', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='phone.plan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='phone.product')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='phone_order_created_e5eb87_idx')],
            },
        ),
    ]
