# Generated by Django 5.2.5 on 2025-08-21 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0013_historicalorder_payment_period_order_payment_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalorder',
            old_name='subsidy_amount_mnp',
            new_name='subsidy_mnp',
        ),
        migrations.RenameField(
            model_name='historicalorder',
            old_name='subsidy_amount',
            new_name='subsidy_standard',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='subsidy_amount_mnp',
            new_name='subsidy_mnp',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='subsidy_amount',
            new_name='subsidy_standard',
        ),
    ]
