# Generated by Django 5.2.5 on 2025-08-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0014_rename_subsidy_amount_mnp_historicalorder_subsidy_mnp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='ga4_id',
            field=models.CharField(blank=True, default='', help_text='GA4 ID', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='ga4_id',
            field=models.CharField(blank=True, default='', help_text='GA4 ID', max_length=255),
        ),
    ]
