# Generated by Django 5.2.5 on 2025-08-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0015_historicalorder_ga4_id_order_ga4_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.FileField(upload_to='policy_documents/')),
                ('effective_date', models.DateField(help_text='Effective date of the policy')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='phone_polic_created_2c74b7_idx')],
            },
        ),
    ]
