# Generated by Django 5.2.5 on 2025-08-08 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0015_banner_faq_notice_review_reviewimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalorder',
            old_name='pio_discount',
            new_name='additional_discount',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='pio_discount',
            new_name='additional_discount',
        ),
        migrations.RenameField(
            model_name='productoption',
            old_name='pio_discount',
            new_name='additional_discount',
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='phone.product'),
            preserve_default=False,
        ),
    ]
