# Generated by Django 5.2.5 on 2025-08-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0016_policydocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policydocument',
            name='title',
        ),
        migrations.AddField(
            model_name='policydocument',
            name='document_type',
            field=models.CharField(choices=[('terms', '이용약관'), ('privacy', '개인정보처리방침')], default='terms', max_length=20),
        ),
    ]
