# Generated by Django 5.2.5 on 2025-09-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0017_remove_policydocument_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, help_text='배너 활성화 여부'),
        ),
        migrations.AddField(
            model_name='banner',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
