# Generated by Django 5.2.5 on 2025-09-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0018_banner_is_active_banner_sort_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('carrier', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=100, null=True)),
                ('link', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('benefits', models.JSONField(default=list)),
                ('open_benefit', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
