# Generated by Django 5.2.5 on 2025-09-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0019_partnercard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnercard',
            name='benefits',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='partnercard',
            name='open_benefit',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
