# Generated by Django 5.2.5 on 2025-09-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0020_alter_partnercard_benefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnercard',
            name='benefit_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
