# Generated by Django 5.2.5 on 2025-09-17 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0021_partnercard_benefit_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnercard',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='partnercard',
            name='open_benefit',
        ),
        migrations.CreateModel(
            name='CardBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('condition', models.CharField(max_length=255, null=True)),
                ('benefit_price', models.IntegerField(default=0)),
                ('is_optional', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_benefits', to='phone.partnercard')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='phone_cardb_created_20ec95_idx')],
            },
        ),
    ]
