# Generated by Django 5.2.5 on 2025-09-17 02:08

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0023_customimage_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
    ]
