# Generated by Django 5.2.5 on 2025-09-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0024_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='event_thumbnails/'),
        ),
    ]
