# Generated by Django 5.2.5 on 2025-09-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0025_event_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicevariant',
            name='name_kt',
            field=models.CharField(blank=True, default='', help_text='KT 모델명', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devicevariant',
            name='name_lg',
            field=models.CharField(blank=True, default='', help_text='LG 모델명', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devicevariant',
            name='name_sk',
            field=models.CharField(blank=True, default='', help_text='SK 모델명', max_length=100, null=True),
        ),
    ]
