# Generated by Django 5.2.5 on 2025-09-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0026_devicevariant_name_kt_devicevariant_name_lg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='sort_order_test',
            field=models.IntegerField(default=0),
        ),
    ]
