# Generated by Django 5.2.5 on 2025-10-16 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0027_banner_sort_order_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPremiumChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('carrier', models.CharField(max_length=10)),
                ('name', models.CharField(help_text='넷플릭스, 유튜브 등', max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='cardbenefit',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='devicecolor',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='devicevariant',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='policydocument',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='productoption',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='banner',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='plan',
            name='membership_level',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('type', models.CharField(choices=[('pc', 'pc'), ('mobile', 'mobile')], default='pc', max_length=25)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='phone.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['created_at'], name='phone_produ_created_7e25a4_idx')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='series',
            field=models.ManyToManyField(related_name='products', to='phone.productseries'),
        ),
        migrations.CreateModel(
            name='DecoratorTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('text_color', models.CharField(max_length=7)),
                ('tag_color', models.CharField(max_length=7)),
                ('product', models.ManyToManyField(to='phone.product')),
                ('productOption', models.ManyToManyField(to='phone.productoption')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['created_at'], name='phone_decor_created_2a6d83_idx')],
            },
        ),
    ]
