# Generated by Django 5.2.5 on 2025-10-16 04:41

import django.db.models.deletion
import phone.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0028_planpremiumchoices_alter_cardbenefit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=phone.utils.UniqueFilePathGenerator('images/')),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_mobile',
            field=models.ImageField(default='', upload_to=phone.utils.UniqueFilePathGenerator('banners/')),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_pc',
            field=models.ImageField(default='', upload_to=phone.utils.UniqueFilePathGenerator('banners/')),
        ),
        migrations.AlterField(
            model_name='customimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=phone.utils.UniqueFilePathGenerator('images/')),
        ),
        migrations.AlterField(
            model_name='devicescolorimage',
            name='image',
            field=models.ImageField(upload_to=phone.utils.UniqueFilePathGenerator('device_color_images/')),
        ),
        migrations.AlterField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=phone.utils.UniqueFilePathGenerator('event_thumbnails/')),
        ),
        migrations.AlterField(
            model_name='partnercard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=phone.utils.UniqueFilePathGenerator('images/')),
        ),
        migrations.AlterField(
            model_name='planpremiumchoices',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=phone.utils.UniqueFilePathGenerator('images/')),
        ),
        migrations.AlterField(
            model_name='policydocument',
            name='content',
            field=models.FileField(upload_to=phone.utils.UniqueFilePathGenerator('policy_documents/')),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_main',
            field=models.ImageField(blank=True, upload_to=phone.utils.UniqueFilePathGenerator('product_images/')),
        ),
        migrations.AlterField(
            model_name='productdetailimage',
            name='image',
            field=models.ImageField(upload_to=phone.utils.UniqueFilePathGenerator('product_images/')),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(upload_to=phone.utils.UniqueFilePathGenerator('product_images/')),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='phone.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, help_text='Review image', null=True, upload_to=phone.utils.UniqueFilePathGenerator('review_images/')),
        ),
    ]
