# Generated by Django 5.2.5 on 2025-10-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0029_alter_banner_image_alter_banner_image_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnercard',
            name='carrier',
            field=models.CharField(choices=[('SK', 'SK Telecom'), ('KT', 'KT Corporation'), ('LG', 'LG Uplus')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='carrier',
            field=models.CharField(choices=[('SK', 'SK Telecom'), ('KT', 'KT Corporation'), ('LG', 'LG Uplus')], max_length=100),
        ),
        migrations.AlterField(
            model_name='planpremiumchoices',
            name='carrier',
            field=models.CharField(choices=[('SK', 'SK Telecom'), ('KT', 'KT Corporation'), ('LG', 'LG Uplus')], max_length=10),
        ),
    ]
