# Generated by Django 5.2.5 on 2025-10-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0030_alter_partnercard_carrier_alter_plan_carrier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.IntegerField(default=0, help_text='조회수'),
        ),
        migrations.AlterField(
            model_name='partnercard',
            name='carrier',
            field=models.CharField(choices=[('SK', 'SK Telecom'), ('KT', 'KT Corporation'), ('LG', 'LG Uplus'), ('MVNO', 'MVNO')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='carrier',
            field=models.CharField(choices=[('SK', 'SK Telecom'), ('KT', 'KT Corporation'), ('LG', 'LG Uplus'), ('MVNO', 'MVNO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='planpremiumchoices',
            name='carrier',
            field=models.CharField(choices=[('SK', 'SK Telecom'), ('KT', 'KT Corporation'), ('LG', 'LG Uplus'), ('MVNO', 'MVNO')], max_length=10),
        ),
    ]
