# Generated by Django 5.2.5 on 2025-10-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0031_product_views_alter_partnercard_carrier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='prev_carrier',
            field=models.CharField(blank=True, choices=[('SK', 'SK'), ('KT', 'KT'), ('LG', 'LG')], help_text='이전 통신사', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='prev_carrier',
            field=models.CharField(blank=True, choices=[('SK', 'SK'), ('KT', 'KT'), ('LG', 'LG')], help_text='이전 통신사', max_length=50, null=True),
        ),
    ]
