# Generated by Django 5.2.5 on 2025-10-27 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0032_historicalorder_prev_carrier_order_prev_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_series', to='phone.productseries'),
        ),
    ]
