# Generated by Django 5.2.5 on 2025-10-27 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0033_product_product_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='series',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productseries', to='phone.productseries'),
        ),
    ]
