# Generated by Django 5.2.5 on 2025-10-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0034_remove_product_series_alter_product_product_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='type',
            field=models.CharField(choices=[('caution', 'caution'), ('event', 'event'), ('general', 'general')], default='general', max_length=25),
        ),
    ]
