# Generated by Django 5.2.5 on 2025-11-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0035_notice_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_main',
        ),
        migrations.AlterField(
            model_name='productimages',
            name='type',
            field=models.CharField(choices=[('pc', 'pc'), ('mobile', 'mobile'), ('detail', 'detail')], default='pc', max_length=25),
        ),
    ]
