# Generated by Django 5.2.5 on 2025-11-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0036_remove_product_image_main_alter_productimages_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetailimage',
            name='type',
            field=models.CharField(choices=[('pc', 'pc'), ('mobile', 'mobile'), ('detail', 'detail')], default='pc', max_length=25),
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
