# Generated by Django 5.2.5 on 2025-11-07 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0037_alter_productdetailimage_type_delete_productimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decoratortag',
            name='productOption',
        ),
    ]
