# Generated by Django 5.2.5 on 2025-11-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0038_remove_decoratortag_productoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecolor',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='decoratortag',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='tags', to='phone.product'),
        ),
    ]
