# Generated by Django 5.2.5 on 2025-11-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0039_devicecolor_sort_order_alter_decoratortag_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productseries',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
