# Generated by Django 5.2.5 on 2025-12-05 07:23

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0040_productseries_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
