# Generated by Django 5.2.5 on 2025-12-08 06:59

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0041_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
