# Generated by Django 5.2.5 on 2025-12-29 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0042_alter_notice_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('carrier', models.CharField(choices=[('SK', 'SK Telecom'), ('KT', 'KT Corporation'), ('LG', 'LG Uplus'), ('MVNO', 'MVNO')], max_length=100)),
                ('final_price', models.IntegerField(blank=True, help_text='최종 가격', null=True)),
                ('price_at', models.DateField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_prices', to='phone.plan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_prices', to='phone.product')),
            ],
            options={
                'unique_together': {('product', 'price_at', 'carrier')},
            },
        ),
    ]
