# Generated by Django 5.2.5 on 2025-12-30 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0043_pricehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceNotificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('customer_phone', models.CharField(max_length=15)),
                ('target_price', models.IntegerField(help_text='Target price for notification')),
                ('is_agreed_in_kakao', models.BooleanField(default=False, help_text='Agreement to receive notifications via KakaoTalk')),
                ('canceld_at', models.DateTimeField(blank=True, help_text='Cancellation timestamp', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_notifications', to='phone.product')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['created_at'], name='phone_price_created_da1621_idx')],
            },
        ),
    ]
