# Generated by Django 5.2.5 on 2025-12-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0044_pricenotificationrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricenotificationrequest',
            name='canceld_at',
        ),
        migrations.RemoveField(
            model_name='pricenotificationrequest',
            name='is_agreed_in_kakao',
        ),
        migrations.AddField(
            model_name='pricenotificationrequest',
            name='notified_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Notification timestamp', null=True),
        ),
        migrations.AddField(
            model_name='pricenotificationrequest',
            name='prev_carrier',
            field=models.CharField(choices=[('SK', 'SK Telecom'), ('KT', 'KT Corporation'), ('LG', 'LG Uplus'), ('MVNO', 'MVNO')], default='MVNO', help_text='Previous carrier', max_length=50),
        ),
    ]
