# Generated by Django 5.2.5 on 2025-12-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0045_remove_pricenotificationrequest_canceld_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricenotificationrequest',
            name='channel_talk_user_id',
            field=models.CharField(blank=True, default='', help_text='Channel Talk User ID for notification', max_length=100, null=True),
        ),
    ]
