# Generated by Django 5.2.5 on 2026-01-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0046_pricenotificationrequest_channel_talk_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicevariant',
            name='price_kt',
            field=models.IntegerField(blank=True, default=0, help_text='KT 모델 가격', null=True),
        ),
        migrations.AddField(
            model_name='devicevariant',
            name='price_lg',
            field=models.IntegerField(blank=True, default=0, help_text='LG 모델 가격', null=True),
        ),
        migrations.AddField(
            model_name='devicevariant',
            name='price_sk',
            field=models.IntegerField(blank=True, default=0, help_text='SK 모델 가격', null=True),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(choices=[('주문접수', '주문접수'), ('해피콜 부재중', '해피콜 부재중'), ('해피콜완료', '해피콜완료'), ('공식신청서접수대기', '공식신청서접수대기'), ('재고대기', '재고대기'), ('신용조회중', '신용조회중'), ('배송요청', '배송요청'), ('배송중', '배송중'), ('배송완료', '배송완료'), ('개통대기', '개통대기'), ('개통완료', '개통완료'), ('취소요청', '취소요청'), ('취소완료', '취소완료')], default='주문접수', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('주문접수', '주문접수'), ('해피콜 부재중', '해피콜 부재중'), ('해피콜완료', '해피콜완료'), ('공식신청서접수대기', '공식신청서접수대기'), ('재고대기', '재고대기'), ('신용조회중', '신용조회중'), ('배송요청', '배송요청'), ('배송중', '배송중'), ('배송완료', '배송완료'), ('개통대기', '개통대기'), ('개통완료', '개통완료'), ('취소요청', '취소요청'), ('취소완료', '취소완료')], default='주문접수', max_length=50),
        ),
        migrations.AlterField(
            model_name='partnercard',
            name='carrier',
            field=models.CharField(choices=[('SK', 'SK'), ('KT', 'KT'), ('LG', 'LG'), ('알뜰폰', '알뜰폰')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='carrier',
            field=models.CharField(choices=[('SK', 'SK'), ('KT', 'KT'), ('LG', 'LG'), ('알뜰폰', '알뜰폰')], max_length=100),
        ),
        migrations.AlterField(
            model_name='planpremiumchoices',
            name='carrier',
            field=models.CharField(choices=[('SK', 'SK'), ('KT', 'KT'), ('LG', 'LG'), ('알뜰폰', '알뜰폰')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='carrier',
            field=models.CharField(choices=[('SK', 'SK'), ('KT', 'KT'), ('LG', 'LG'), ('알뜰폰', '알뜰폰')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pricenotificationrequest',
            name='prev_carrier',
            field=models.CharField(choices=[('SK', 'SK'), ('KT', 'KT'), ('LG', 'LG'), ('알뜰폰', '알뜰폰')], default='알뜰폰', help_text='Previous carrier', max_length=50),
        ),
    ]
