# Generated by Django 5.2.5 on 2026-01-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0047_devicevariant_price_kt_devicevariant_price_lg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='device_price',
            field=models.IntegerField(default=0, help_text='기기 가격', null=True),
        ),
    ]
