# Generated by Django 5.2.5 on 2026-01-12 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0048_productoption_device_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='contract_type',
            field=models.CharField(choices=[('신규', '신규'), ('번호이동', '번호이동'), ('기기변경', '기기변경')], default='기기변경', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='contract_type',
            field=models.CharField(choices=[('신규', '신규'), ('번호이동', '번호이동'), ('기기변경', '기기변경')], default='기기변경', max_length=50),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='contract_type',
            field=models.CharField(choices=[('신규', '신규'), ('번호이동', '번호이동'), ('기기변경', '기기변경')], default='기기변경', max_length=50),
        ),
        migrations.CreateModel(
            name='CreditCheckAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('carrier', models.CharField(choices=[('SK', 'SK'), ('KT', 'KT'), ('LG', 'LG'), ('알뜰폰', '알뜰폰')], max_length=50)),
                ('link', models.URLField(help_text='Credit check agreement link')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['created_at'], name='phone_credi_created_f0a486_idx')],
            },
        ),
        migrations.CreateModel(
            name='Delearship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('carrier', models.CharField(choices=[('SK', 'SK'), ('KT', 'KT'), ('LG', 'LG'), ('알뜰폰', '알뜰폰')], max_length=50)),
                ('contact_number', models.CharField(max_length=20)),
                ('manager', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['created_at'], name='phone_delea_created_7f414f_idx')],
            },
        ),
        migrations.AddField(
            model_name='productoption',
            name='delear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_options', to='phone.delearship'),
        ),
        migrations.CreateModel(
            name='OfficialContractLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('contract_type', models.CharField(choices=[('신규', '신규'), ('번호이동', '번호이동'), ('기기변경', '기기변경')], default='기기변경', max_length=50)),
                ('link', models.URLField(help_text='Official contract submission link')),
                ('delear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_links', to='phone.delearship')),
                ('device_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_links', to='phone.devicevariant')),
            ],
            options={
                'unique_together': {('delear', 'device_variant', 'contract_type')},
            },
        ),
        migrations.AddField(
            model_name='productoption',
            name='official_contract_link',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_options', to='phone.officialcontractlink'),
        ),
    ]
