# Generated by Django 5.2.5 on 2026-01-16 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0049_alter_historicalorder_contract_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Delearship',
            new_name='Dealership',
        ),
        migrations.RenameField(
            model_name='officialcontractlink',
            old_name='delear',
            new_name='dealer',
        ),
        migrations.RenameField(
            model_name='productoption',
            old_name='delear',
            new_name='dealer',
        ),
        migrations.RenameIndex(
            model_name='dealership',
            new_name='phone_deale_created_adb789_idx',
            old_name='phone_delea_created_7f414f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='officialcontractlink',
            unique_together={('dealer', 'device_variant', 'contract_type')},
        ),
    ]
