# Generated by Django 5.2.5 on 2026-01-16 04:11

import django.db.models.deletion
import phone.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0050_rename_delearship_dealership_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=phone.utils.UniqueFilePathGenerator('images/'))),
                ('name_in_sheet', models.CharField(max_length=100)),
                ('carrier', models.CharField(choices=[('SK', 'SK'), ('KT', 'KT'), ('LG', 'LG'), ('알뜰폰', '알뜰폰')], max_length=50)),
                ('color_in_sheet', models.CharField(max_length=50)),
                ('stock_count', models.IntegerField(default=0)),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='phone.dealership')),
                ('device_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='phone.devicecolor')),
                ('device_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='phone.devicevariant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
