# Generated by Django 5.2.5 on 2026-01-16 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('phone', '0051_inventory'), ('phone', '0052_alter_inventory_options_remove_inventory_image_and_more'), ('phone', '0053_rename_stock_count_inventory_count_and_more')]

    dependencies = [
        ('phone', '0050_rename_delearship_dealership_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name_in_sheet', models.CharField(max_length=100)),
                ('color_in_sheet', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0)),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='phone.dealership')),
                ('device_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='phone.devicecolor')),
                ('device_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='phone.devicevariant')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['created_at'], name='phone_inven_created_91ad48_idx')],
            },
        ),
    ]
