# Generated by Django 5.2.5 on 2026-01-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0051_inventory_squashed_0053_rename_stock_count_inventory_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='color_in_sheet',
            field=models.CharField(help_text='재고표에 있는 색상명. 텍스트 안에 쉼표가 들어가서 여러 색상명이 있을 수 있음', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name_in_sheet',
            field=models.CharField(help_text='재고표에 있는 모델명. 텍스트 안에 쉼표가 들어가서 여러 모델명이 있을 수 있음', max_length=100),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['device_variant', 'device_color', 'dealership'], name='phone_inven_device__966257_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('device_variant', 'device_color', 'dealership'), name='unique_inventory_item'),
        ),
    ]
