# Generated by Django 5.2.5 on 2026-01-21 04:12

import phone.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0054_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='credit_check_agreement',
            field=models.TextField(blank=True, help_text='신용조회 동의서 스크린샷', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='credit_check_agreement',
            field=models.ImageField(blank=True, help_text='신용조회 동의서 스크린샷', null=True, upload_to=phone.utils.UniqueFilePathGenerator('credit_check_agreements/')),
        ),
    ]
