# Generated by Django 5.2.5 on 2026-01-21 07:58

import django.db.models.deletion
import phone.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0055_historicalorder_credit_check_agreement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcheckagreement',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='creditcheckagreement',
            name='link',
        ),
        migrations.RemoveField(
            model_name='historicalorder',
            name='credit_check_agreement',
        ),
        migrations.RemoveField(
            model_name='order',
            name='credit_check_agreement',
        ),
        migrations.AddField(
            model_name='creditcheckagreement',
            name='image',
            field=models.ImageField(blank=True, help_text='신용조회 동의서 스크린샷', null=True, upload_to=phone.utils.UniqueFilePathGenerator('credit_check_agreements/')),
        ),
        migrations.AddField(
            model_name='creditcheckagreement',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='credit_check_agreements', to='phone.order'),
            preserve_default=False,
        ),
    ]
