# Generated by Django 5.2.5 on 2026-01-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0056_remove_creditcheckagreement_carrier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealership',
            name='credit_check_agree_format',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dealership',
            name='opening_request_format',
            field=models.TextField(null=True),
        ),
    ]
