# Generated by Django 5.2.5 on 2026-01-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0057_dealership_credit_check_agree_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='channeltalk_user_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='channeltalk_user_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
