# Generated by Django 5.2.5 on 2026-02-19 09:18

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0058_historicalorder_channeltalk_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('11번가', '11번가'), ('G마켓 옥션', 'G마켓 옥션'), ('SSG', 'SSG'), ('롯데ON', '롯데ON')], default='11번가', max_length=20, verbose_name='오픈마켓업체')),
                ('option_min_rate', models.IntegerField(default=0)),
                ('option_max_rate', models.IntegerField(default=0)),
                ('commision_rate_default', models.FloatField(default=0.08)),
                ('commision_rate_compare_platform', models.FloatField(default=0.02)),
                ('api_key', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['created_at'], name='phone_openm_created_c6c16d_idx')],
            },
        ),
        migrations.CreateModel(
            name='OpenMarketProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('om_product_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('default_price', models.PositiveIntegerField(default=10000)),
                ('detail_page_html', tinymce.models.HTMLField(blank=True, default='')),
                ('open_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='phone.openmarket')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='OpenMarketProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('om_id', models.CharField(blank=True, default='', max_length=255)),
                ('option_name', models.CharField(blank=True, default='', max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('inventory', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_market_options', to='phone.inventory')),
                ('open_market_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='phone.openmarketproduct')),
                ('pio_product_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_market_options', to='phone.productoption')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.AddIndex(
            model_name='openmarketproduct',
            index=models.Index(fields=['created_at'], name='phone_openm_created_b145e0_idx'),
        ),
        migrations.AddIndex(
            model_name='openmarketproductoption',
            index=models.Index(fields=['created_at'], name='phone_openm_created_0be33b_idx'),
        ),
    ]
