# Generated by Django 5.2.5 on 2026-02-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0059_openmarket_openmarketproduct_openmarketproductoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openmarketproduct',
            name='seller_code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
