# Generated by Django 5.2.5 on 2026-02-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0060_openmarketproduct_seller_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openmarketproduct',
            old_name='default_price',
            new_name='registered_price',
        ),
        migrations.AddField(
            model_name='openmarketproduct',
            name='last_price_updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
