# Generated by Django 5.2.5 on 2026-02-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0061_rename_default_price_openmarketproduct_registered_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
