# Generated by Django 5.2.5 on 2026-02-23 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0062_plan_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='openmarketproduct',
            name='device_variant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_market_product', to='phone.devicevariant'),
        ),
    ]
