# Generated by Django 5.2.5 on 2026-02-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0063_openmarketproduct_device_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenMarketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('11번가', '11번가'), ('G마켓 옥션', 'G마켓 옥션'), ('SSG', 'SSG'), ('롯데ON', '롯데ON')], max_length=20, verbose_name='오픈마켓')),
                ('order_no', models.CharField(max_length=255, verbose_name='주문번호')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('source', 'order_no')},
            },
        ),
    ]
