# Generated by Django 5.2.5 on 2026-03-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0064_openmarketorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('prev_carrier', models.CharField(max_length=50)),
                ('keep_carrier', models.BooleanField(default=False)),
                ('device_name', models.CharField(max_length=100)),
                ('data_usage', models.CharField(max_length=50)),
                ('internet', models.CharField(max_length=50)),
                ('family_bundle', models.BooleanField(default=False)),
                ('gift', models.BooleanField(default=False)),
                ('card', models.BooleanField(default=False)),
                ('internet_new', models.BooleanField(default=False)),
                ('selfbuy_total', models.IntegerField(default=0)),
                ('pio_total', models.IntegerField(default=0)),
                ('total_saving', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_carrier', models.CharField(max_length=50)),
                ('keep_carrier', models.BooleanField(default=False)),
                ('device_name', models.CharField(max_length=100)),
                ('data_usage', models.CharField(max_length=50)),
                ('internet', models.CharField(max_length=50)),
                ('family_bundle', models.BooleanField(default=False)),
                ('gift', models.BooleanField(default=False)),
                ('card', models.BooleanField(default=False)),
                ('internet_new', models.BooleanField(default=False)),
                ('selfbuy_total', models.IntegerField(default=0)),
                ('pio_total', models.IntegerField(default=0)),
                ('total_saving', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ga4_id', models.CharField(blank=True, default='', help_text='GA4 ID', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='openmarket',
            name='source',
            field=models.CharField(choices=[('11번가', '11번가'), ('G마켓 옥션', 'G마켓 옥션'), ('SSG', 'SSG'), ('롯데ON', '롯데ON'), ('네이버 가격비교', '네이버 가격비교')], default='11번가', max_length=20, verbose_name='오픈마켓업체'),
        ),
        migrations.AlterField(
            model_name='openmarketorder',
            name='source',
            field=models.CharField(choices=[('11번가', '11번가'), ('G마켓 옥션', 'G마켓 옥션'), ('SSG', 'SSG'), ('롯데ON', '롯데ON'), ('네이버 가격비교', '네이버 가격비교')], max_length=20, verbose_name='오픈마켓'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='discount_type',
            field=models.CharField(choices=[('공시지원금', '공시지원금'), ('선택약정', '선택약정')], default='공시지원금', max_length=50),
        ),
    ]
