# Generated by Django 5.2.5 on 2026-04-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phone", "0069_partner_card_redesign"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cardadditionalpromotion",
            options={},
        ),
        migrations.AlterModelOptions(
            name="partnercard",
            options={},
        ),
        migrations.RenameIndex(
            model_name="cardissuer",
            new_name="phone_cardi_created_6eb550_idx",
            old_name="phone_cardi_created_5c6d18_idx",
        ),
        migrations.AlterField(
            model_name="cardadditionalpromotion",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="cardissuer",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
