# Generated by Django 5.2.5 on 2026-04-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phone", "0070_alter_cardadditionalpromotion_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnercard",
            name="contact",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="partnercard",
            name="extra_benefits",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="partnercard",
            name="signup_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
