# Generated by Django 5.2.5 on 2026-04-29 03:10

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internet", "0013_inquiry"),
        ("phone", "0072_seed_partner_cards"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalculatorSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "funnel_variant",
                    models.CharField(
                        choices=[("control", "control"), ("v1", "v1"), ("v3", "v3")],
                        default="control",
                        max_length=20,
                    ),
                ),
                ("copy_variant", models.CharField(default="v2", max_length=50)),
                ("pricing_path", models.CharField(default="selfbuy_v1", max_length=50)),
                (
                    "copy_variant_v3",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contact_channel",
                    models.CharField(
                        blank=True,
                        choices=[("phone", "phone"), ("kakao", "kakao")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("name_field_omitted", models.BooleanField(default=False)),
                (
                    "carrier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SK", "SK"),
                            ("KT", "KT"),
                            ("LG", "LG"),
                            ("알뜰폰", "알뜰폰"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("keep_carrier", models.BooleanField(null=True)),
                (
                    "device_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("family_bundle", models.BooleanField(null=True)),
                ("gift", models.BooleanField(null=True)),
                ("data_usage", models.CharField(blank=True, max_length=20, null=True)),
                ("plan_price_mvno", models.IntegerField(null=True)),
                ("plan_price_mno", models.IntegerField(null=True)),
                ("card", models.BooleanField(null=True)),
                ("card_spend", models.IntegerField(null=True)),
                (
                    "card_history",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("internet_new", models.BooleanField(null=True)),
                ("device_price", models.IntegerField(default=0)),
                ("public_subsidy", models.IntegerField(default=0)),
                ("additional_discount", models.IntegerField(default=0)),
                ("skt_plan_id", models.CharField(blank=True, max_length=50, null=True)),
                ("skt_plan_monthly_fee", models.IntegerField(default=0)),
                (
                    "static_card_recommended",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("static_card_monthly", models.IntegerField(default=0)),
                ("static_card_total24", models.IntegerField(default=0)),
                ("partner_card_slots", models.JSONField(blank=True, default=list)),
                ("partner_card_monthly", models.IntegerField(default=0)),
                ("partner_card_total24", models.IntegerField(default=0)),
                ("final_card_total24", models.IntegerField(default=0)),
                ("final_card_monthly", models.IntegerField(default=0)),
                ("family_bundle_eligible", models.BooleanField(default=False)),
                ("gift_eligible", models.BooleanField(default=False)),
                ("internet_new_eligible", models.BooleanField(default=False)),
                ("pio_total", models.IntegerField(default=0)),
                ("selfbuy_total", models.IntegerField(default=0)),
                ("official_total", models.IntegerField(default=0)),
                ("benefit_only", models.IntegerField(default=0)),
                ("total_saving", models.IntegerField(default=0)),
                ("official_vs_pio", models.IntegerField(default=0)),
                (
                    "winner",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pio", "pio"),
                            ("selfBuy", "selfBuy"),
                            ("official", "official"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("ranks", models.JSONField(blank=True, default=list)),
                (
                    "benefit_amounts_snapshot",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "submitted_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "submitted_contact",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "ga4_client_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calculator_sessions",
                        to="phone.product",
                    ),
                ),
                (
                    "internet_carriers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="calculator_sessions",
                        to="internet.internetcarrier",
                    ),
                ),
            ],
            options={
                "db_table": "calculator_session",
            },
        ),
        migrations.CreateModel(
            name="CustomerIdentity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("name_phone", "name_phone"),
                            ("naver_oauth", "naver_oauth"),
                            ("kakao_oauth", "kakao_oauth"),
                        ],
                        default="name_phone",
                        max_length=20,
                    ),
                ),
                ("pre_name", models.CharField(max_length=50)),
                ("pre_contact", models.CharField(max_length=20)),
                ("identified_at", models.DateTimeField()),
                (
                    "oauth_provider",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "oauth_user_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "oauth_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("oauth_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("oauth_raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity",
                        to="phone.calculatorsession",
                    ),
                ),
            ],
            options={
                "db_table": "customer_identity",
            },
        ),
        migrations.AddIndex(
            model_name="calculatorsession",
            index=models.Index(
                fields=["funnel_variant", "contact_channel"],
                name="calculator__funnel__609f24_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="calculatorsession",
            index=models.Index(
                fields=["ga4_client_id"], name="calculator__ga4_cli_0ed52e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calculatorsession",
            index=models.Index(
                condition=models.Q(("contact_channel__isnull", False)),
                fields=["contact_channel"],
                name="cs_lead_partial",
            ),
        ),
        migrations.AddIndex(
            model_name="customeridentity",
            index=models.Index(
                fields=["oauth_provider", "oauth_user_id"],
                name="customer_id_oauth_p_bdad9a_idx",
            ),
        ),
    ]
