# Generated by Django 5.2.5 on 2026-05-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phone", "0073_calculatorsession_customeridentity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicevariant",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="자급제 카드 등 단말 단위 노출 시 대표로 사용할 variant (Device당 1개 권장)",
            ),
        ),
        migrations.AddField(
            model_name="devicevariant",
            name="self_buy_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="자급제 구매 링크 (제조사몰 등). 용량별로 다른 링크 입력",
                max_length=500,
            ),
        ),
    ]
