# Generated by Django 5.2.5 on 2026-05-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phone", "0074_devicevariant_is_default_devicevariant_self_buy_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="devicevariant",
            name="self_buy_url",
        ),
        migrations.AddField(
            model_name="devicevariant",
            name="self_buy_url_coupang",
            field=models.URLField(
                blank=True,
                default="",
                help_text="자급제 구매 링크 (쿠팡). 용량별로 다른 링크 입력",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="devicevariant",
            name="self_buy_url_naver",
            field=models.URLField(
                blank=True,
                default="",
                help_text="자급제 구매 링크 (네이버). 용량별로 다른 링크 입력",
                max_length=500,
            ),
        ),
    ]
