# Generated by Django 5.2.5 on 2026-05-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phone", "0075_remove_devicevariant_self_buy_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openmarketproduct",
            name="registered_price",
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
