# Generated by Django 5.2.5 on 2026-07-02 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0076_change_registered_price_default_to_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySummary',
            fields=[
            ],
            options={
                'verbose_name': '제품별 재고',
                'verbose_name_plural': '제품별 재고',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('phone.inventory',),
        ),
    ]
