# Generated by Django 5.2.5 on 2026-07-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phone", "0077_inventorysummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="openmarketproduct",
            name="is_display_stopped",
            field=models.BooleanField(
                default=False,
                help_text="재고 소진 시 11번가 전시중지(True), 재고 확보 시 전시재개(False). 재고 동기화 시 자동 갱신됨.",
                verbose_name="11번가 전시중지 여부",
            ),
        ),
    ]
