# Generated by Django 5.2.5 on 2026-07-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phone", "0078_openmarketproduct_is_display_stopped"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenMarketSettlement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("11번가", "11번가"),
                            ("G마켓 옥션", "G마켓 옥션"),
                            ("SSG", "SSG"),
                            ("롯데ON", "롯데ON"),
                            ("네이버 가격비교", "네이버 가격비교"),
                        ],
                        max_length=20,
                        verbose_name="오픈마켓",
                    ),
                ),
                ("order_no", models.CharField(max_length=255, verbose_name="주문번호")),
                (
                    "ord_prd_seq",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="주문순번"
                    ),
                ),
                (
                    "claim_req_seq",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="클레임번호"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="상품명"
                    ),
                ),
                (
                    "settlement_amount",
                    models.IntegerField(default=0, verbose_name="정산금액"),
                ),
                (
                    "settlement_day",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="정산일"
                    ),
                ),
                (
                    "remittance_plan_day",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="송금예정일"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {
                    ("source", "order_no", "ord_prd_seq", "claim_req_seq")
                },
            },
        ),
    ]
