# Generated by Django 5.2.5 on 2026-07-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phone", "0079_openmarketsettlement"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicevariant",
            name="gtin",
            field=models.CharField(
                blank=True,
                default="",
                help_text="GTIN(바코드, EAN-13/UPC 등). 용량별로 다름. Google Merchant 리뷰 매칭 키.",
                max_length=14,
            ),
        ),
    ]
