# Generated by Django 5.2.5 on 2026-07-09 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phone", "0079_openmarketsettlement"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceSpecItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "label",
                    models.CharField(help_text="예: 디스플레이, 칩셋", max_length=50),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="예: 6.1형 Super Retina XDR OLED", max_length=200
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specs",
                        to="phone.device",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
