# Generated by Django 5.2.5 on 2026-07-09 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("phone", "0080_devicevariant_gtin"),
        ("phone", "0081_seed_device_specs"),
    ]

    operations = []
