"""Auto-generated PartnerCard seed data — DO NOT EDIT BY HAND.

Source     : .omc/output/card_list_merged.json
Generator  : .omc/scripts/generate_seed_module.py
Used by    : phone/migrations/0072_seed_partner_cards.py
"""

PARTNER_CARDS = [ { 'name': 'T PREMIUM 삼성카드',
    'carriers': ['SK'],
    'issuer': '삼성',
    'discount_types': ['할부'],
    'annual_fee': 25000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '',
    'min_installment_amount': None,
    'installment_excluded_items': '장기카드대출(카드론)\n'
                                  '단기카드대출(현금서비스)\n'
                                  '각종 수수료 및 이자\n'
                                  '연체료\n'
                                  '연회비 납부건\n'
                                  '아파트 관리비\n'
                                  '대학 등록금\n'
                                  '유치원 납입금\n'
                                  '초/중/고등학교 학교 납입금 등',
    'contact': '',
    'signup_url': '',
    'extra_benefits': '커피전문점 5% 청구할인\n편의점/배달앱 5% 청구할인',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [ {'threshold': 800000, 'amount': 25000},
                        {'threshold': 1600000, 'amount': 40000},
                        {'threshold': 2500000, 'amount': 60000}],
    'benefits_additional': [ {'threshold': 800000, 'amount': 10000},
                             {'threshold': 1600000, 'amount': 10000},
                             {'threshold': 2500000, 'amount': 10000}],
    'cashback_promo': { 'title': '갤럭시 S26 시리즈 캐시백',
                        'description': '갤럭시 S26 시리즈 50만원 이상 할부 결제 및 프로모션1 조건 충족 시',
                        'cashback_amount': 120000,
                        'min_installment_amount': 500000,
                        'target_series_ids': [7],
                        'payment_date_text': '2026-06-24',
                        'is_active': True,
                        'sort_order': 0}},
  { 'name': 'T라이트 삼성카드',
    'carriers': ['SK'],
    'issuer': '삼성',
    'discount_types': ['할부'],
    'annual_fee': 25000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '',
    'min_installment_amount': None,
    'installment_excluded_items': '4대 보험 및 장애인 고용부담금\n무이자할부\n현금서비스\n국세\n지방세\n아파트 관리비\n기프트/선불카드 구매 및 충전\n상품권 구매\n대중교통 등',
    'contact': '',
    'signup_url': '',
    'extra_benefits': '커피전문점 5% 청구할인\n편의점/배달앱 5% 청구할인\n삼성 단말기 전용카드',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [ {'threshold': 400000, 'amount': 10000},
                        {'threshold': 800000, 'amount': 15000},
                        {'threshold': 1200000, 'amount': 20000}],
    'benefits_additional': [ {'threshold': 400000, 'amount': 12000},
                             {'threshold': 800000, 'amount': 8000},
                             {'threshold': 1200000, 'amount': 4000}],
    'cashback_promo': { 'title': '갤럭시 S26 시리즈 캐시백',
                        'description': '갤럭시 S26 시리즈 50만원 이상 라이트 할부 조건 충족 시',
                        'cashback_amount': 80000,
                        'min_installment_amount': 500000,
                        'target_series_ids': [7],
                        'payment_date_text': '2026-06-24',
                        'is_active': True,
                        'sort_order': 0}},
  { 'name': 'T 라이트 KB국민카드',
    'carriers': ['SK'],
    'issuer': 'KB국민',
    'discount_types': ['할부'],
    'annual_fee': 20000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '',
    'min_installment_amount': None,
    'installment_excluded_items': '(부분)무이자할부 이용금액\n단기카드대출\n장기카드대출\n국세\n지방세\n공과금(전기/수도)\n아파트관리비\n초/중/고 학교납입금 전체 등',
    'contact': '',
    'signup_url': '',
    'extra_benefits': 'KBpay 3만원 이상 결제 시 3만원 추가 캐시백 (2026-04-01 ~ 2026-05-15)\n'
                      '정기결제 건수에 따라 월 최대 3,000원 추가 할인(아파트 관리비, 4대보험 등)',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [ {'threshold': 300000, 'amount': 8000},
                        {'threshold': 700000, 'amount': 12000},
                        {'threshold': 1000000, 'amount': 14000}],
    'benefits_additional': [ {'threshold': 300000, 'amount': 15000},
                             {'threshold': 700000, 'amount': 12000},
                             {'threshold': 1000000, 'amount': 11000}],
    'cashback_promo': { 'title': '갤럭시 S26 시리즈 캐시백',
                        'description': '갤럭시 S26 시리즈 50만원 이상 라이트 할부 조건 충족 시',
                        'cashback_amount': 80000,
                        'min_installment_amount': 500000,
                        'target_series_ids': [7],
                        'payment_date_text': '2026-06-19',
                        'is_active': True,
                        'sort_order': 0}},
  { 'name': '우리카드 T라이트',
    'carriers': ['SK'],
    'issuer': '우리',
    'discount_types': ['할부'],
    'annual_fee': 25000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '',
    'min_installment_amount': None,
    'installment_excluded_items': '아파트 관리비\nLH/SH임대료\n정부지원금\n대학 등록금\n국세/지방세\n공공요금\n단기/장기카드대출 등',
    'contact': '',
    'signup_url': '',
    'extra_benefits': '',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [ {'threshold': 400000, 'amount': 10000},
                        {'threshold': 800000, 'amount': 15000},
                        {'threshold': 1200000, 'amount': 20000}],
    'benefits_additional': [ {'threshold': 400000, 'amount': 18000},
                             {'threshold': 800000, 'amount': 14000},
                             {'threshold': 1200000, 'amount': 10000}],
    'cashback_promo': None},
  { 'name': 'T라이트 신한카드',
    'carriers': ['SK'],
    'issuer': '신한',
    'discount_types': ['할부'],
    'annual_fee': 12000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '',
    'min_installment_amount': None,
    'installment_excluded_items': '현금서비스\n카드론\n연회비\n이자\n선불카드충전실적\n무이자 할부 등',
    'contact': '',
    'signup_url': '',
    'extra_benefits': '',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [{'threshold': 300000, 'amount': 10000}, {'threshold': 700000, 'amount': 15000}],
    'benefits_additional': [{'threshold': 300000, 'amount': 13000}, {'threshold': 700000, 'amount': 10000}],
    'cashback_promo': { 'title': '갤럭시 S26 시리즈 캐시백',
                        'description': '갤럭시 S26 시리즈 50만원 이상 할부 결제 및 프로모션1 충족 시',
                        'cashback_amount': 100000,
                        'min_installment_amount': 500000,
                        'target_series_ids': [7],
                        'payment_date_text': '2026-05-29',
                        'is_active': True,
                        'sort_order': 0}},
  { 'name': '신한 파인애플 카드 (아이폰 전용)',
    'carriers': ['SK'],
    'issuer': '신한',
    'discount_types': ['할부'],
    'annual_fee': 20000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '',
    'min_installment_amount': None,
    'installment_excluded_items': '',
    'contact': '',
    'signup_url': '',
    'extra_benefits': '영화예매 최대 3천원 할인\n주유 리터당 40원 적립\n놀이공원 50% 할인\nLG트윈스 2천원 할인',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [{'threshold': 300000, 'amount': 10000}, {'threshold': 800000, 'amount': 15000}],
    'benefits_additional': [{'threshold': 300000, 'amount': 13000}, {'threshold': 700000, 'amount': 25000}],
    'cashback_promo': None},
  { 'name': '텔로 T라이트 롯데카드',
    'carriers': ['SK'],
    'issuer': '롯데',
    'discount_types': ['할부'],
    'annual_fee': 20000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '',
    'min_installment_amount': None,
    'installment_excluded_items': 'SKT 통신요금\n텔로 T 라이트 외 롯데카드 이용금액\n모든 무이자할부\n국세/지방세\n4대보험\n초/중/고교 납입금 등',
    'contact': '',
    'signup_url': '',
    'extra_benefits': '롯데백화점 5% 할인쿠폰\n롯데시네마 1,500원 할인\n롯데리아/엔제리너스 1,000원당 50원 할인',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [{'threshold': 400000, 'amount': 10000}, {'threshold': 800000, 'amount': 13000}],
    'benefits_additional': [{'threshold': 400000, 'amount': 13000}, {'threshold': 800000, 'amount': 12000}],
    'cashback_promo': { 'title': '갤럭시 S26 시리즈 캐시백',
                        'description': '갤럭시 S26 시리즈 60만원 이상 할부 결제 및 프로모션1 충족 시',
                        'cashback_amount': 100000,
                        'min_installment_amount': 600000,
                        'target_series_ids': [7],
                        'payment_date_text': '2026-06-19',
                        'is_active': True,
                        'sort_order': 0}},
  { 'name': 'NH농협 T라이트카드',
    'carriers': ['SK'],
    'issuer': 'NH농협',
    'discount_types': ['할부'],
    'annual_fee': 15000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '',
    'min_installment_amount': None,
    'installment_excluded_items': '대학 등록금\n교육비\n임대료\n각종 세금 및 공과금\n사회보험\n아파트관리비\n도시가스\n선불카드 구매액\n카드론 등',
    'contact': '',
    'signup_url': '',
    'extra_benefits': '커피/베이커리/아이스크림 1천원 청구할인\nCGV 1천원 청구할인\n주요 놀이공원 50% 할인',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [{'threshold': 400000, 'amount': 11000}, {'threshold': 700000, 'amount': 17000}],
    'benefits_additional': [{'threshold': 400000, 'amount': 18000}, {'threshold': 800000, 'amount': 35000}],
    'cashback_promo': None},
  { 'name': '현대카드 M Edition3 (T라이트2)',
    'carriers': ['SK'],
    'issuer': '현대',
    'discount_types': ['할부'],
    'annual_fee': 20000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '',
    'min_installment_amount': None,
    'installment_excluded_items': 'SKT 라이트할부 이용금액\n장/단기카드대출\n연회비\n제수수료\n공과금/4대보험\n전기/도시가스\n아파트관리비\n초중고대학 등록금\n상품권 등',
    'contact': '',
    'signup_url': '',
    'extra_benefits': '24개월 이후 M포인트 적립 가능\n애플페이 이용 가능',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [{'threshold': 500000, 'amount': 15000}, {'threshold': 1000000, 'amount': 25000}],
    'benefits_additional': [{'threshold': 500000, 'amount': 17000}, {'threshold': 1000000, 'amount': 9000}],
    'cashback_promo': None},
  { 'name': 'T나는 혜택 삼성카드',
    'carriers': ['SK'],
    'issuer': '삼성',
    'discount_types': ['할부', '유선청구', '무선청구'],
    'annual_fee': 20000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '2026-04-30 이내 자동이체 승인(매월 1.5만원 이상) 필수',
    'min_installment_amount': None,
    'installment_excluded_items': '무이자할부\n건강/국민/고용/산재보험\n국세/지방세/공과금\n학교납입금\n대학 등록금\n대중교통\n택시\n아파트 관리비\n부동산 임대료\n상품권 등',
    'contact': '',
    'signup_url': '',
    'extra_benefits': '정기결제 건수에 따라 월 1,000~3,000원 추가 할인',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [ {'threshold': 300000, 'amount': 7000},
                        {'threshold': 700000, 'amount': 10000},
                        {'threshold': 1200000, 'amount': 13000}],
    'benefits_additional': [ {'threshold': 300000, 'amount': 13000},
                             {'threshold': 700000, 'amount': 11000},
                             {'threshold': 1200000, 'amount': 9000}],
    'cashback_promo': None},
  { 'name': 'TELLO SE 롯데카드',
    'carriers': ['SK'],
    'issuer': '롯데',
    'discount_types': ['유선청구', '무선청구'],
    'annual_fee': 25000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '',
    'min_installment_amount': None,
    'installment_excluded_items': 'SKT 통신요금\n무이자 할부\n아파트 관리비\n월세\n상품권\n정부지원금\n카드론\n국세/지방세\n공과금\n4대보험 등',
    'contact': '',
    'signup_url': '',
    'extra_benefits': '롯데백화점 5% 쿠폰\n롯데월드 50% 할인\nL.POINT 적립',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [{'threshold': 400000, 'amount': 8000}, {'threshold': 800000, 'amount': 13000}],
    'benefits_additional': [{'threshold': 400000, 'amount': 14000}, {'threshold': 800000, 'amount': 11000}],
    'cashback_promo': None},
  { 'name': 'T 이코노미 KB 국민카드',
    'carriers': ['SK'],
    'issuer': 'KB국민',
    'discount_types': ['유선청구', '무선청구'],
    'annual_fee': 15000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '',
    'min_installment_amount': None,
    'installment_excluded_items': '해당 카드로 할인받은 이용건 전체\n무이자할부\n단기/장기카드대출\n각종 세금 및 공과금\n아파트관리비 등',
    'contact': '',
    'signup_url': '',
    'extra_benefits': '자동이체 발생 익월부터 최대 24개월 추가할인',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [{'threshold': 300000, 'amount': 12000}, {'threshold': 700000, 'amount': 17000}],
    'benefits_additional': [{'threshold': 200000, 'amount': 10000}],
    'cashback_promo': None},
  { 'name': '하나 CLUB SK',
    'carriers': ['SK'],
    'issuer': '하나',
    'discount_types': ['무선청구'],
    'annual_fee': 9000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': None,
    'add_discount_months': 24,
    'add_discount_condition': '[모바일카드 기준 혜택. 일반 카드 발급 시 별도 혜택]',
    'min_installment_amount': None,
    'installment_excluded_items': 'SK통신요금\nSK주유소/충전소 이용금액\n아파트관리비\n국세\n지방세\n등록금 등',
    'contact': '',
    'signup_url': '',
    'extra_benefits': 'SK주유소 리터당 최대 150원 할인\n'
                      '영화(CGV/롯데/메가박스) 최대 3,000원 할인\n'
                      '외식(아웃백/TGIF) 5~10% 청구할인\n'
                      '커피 2.5~5% 할인\n'
                      '대중교통 3.5~7% 청구할인',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [ {'threshold': 400000, 'amount': 5000},
                        {'threshold': 700000, 'amount': 10000},
                        {'threshold': 1000000, 'amount': 15000}],
    'benefits_additional': [],
    'cashback_promo': None},
  { 'name': 'U+ 삼성카드 (U+ 라이트 삼성카드)',
    'carriers': ['LG'],
    'issuer': '삼성',
    'discount_types': ['할부', '유선청구', '무선청구'],
    'annual_fee': 20000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '',
    'min_installment_amount': None,
    'installment_excluded_items': '현금서비스\n'
                                  '카드론\n'
                                  '각종 수수료 및 이자\n'
                                  '연회비\n'
                                  '연체료\n'
                                  '대중교통\n'
                                  '택시\n'
                                  '아파트 관리비\n'
                                  '부동산 임대료\n'
                                  '상품권 구매\n'
                                  '4대보험료\n'
                                  '지방세/국세\n'
                                  '기프트/선불카드 구매 및 충전\n'
                                  '수도/전기요금\n'
                                  '장애인고용부담금\n'
                                  '대학등록금\n'
                                  '초·중·고 학교 납입금',
    'contact': '1644-2866',
    'signup_url': '',
    'extra_benefits': 'JCB 브랜드 발급 시 1.5만원 추가 캐시백\n'
                      '생활요금 자동납부 시 월 최대 3,000원 할인 (아파트관리비, 보험료, 렌탈 등)\n'
                      '커피전문점 5% 할인\n'
                      '편의점/배달앱 5% 할인',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [ {'threshold': 300000, 'amount': 7000},
                        {'threshold': 700000, 'amount': 10000},
                        {'threshold': 1200000, 'amount': 13000}],
    'benefits_additional': [ {'threshold': 300000, 'amount': 13000},
                             {'threshold': 700000, 'amount': 11000},
                             {'threshold': 1200000, 'amount': 9000}],
    'cashback_promo': { 'title': '갤럭시 S26 시리즈 캐시백',
                        'description': '갤럭시 S26 시리즈 장기할부 30만원 이상 결제 및 자동이체 등록 시',
                        'cashback_amount': 100000,
                        'min_installment_amount': 300000,
                        'target_series_ids': [7],
                        'payment_date_text': '',
                        'is_active': True,
                        'sort_order': 0}},
  { 'name': 'M Edition3 (통신할인형 2.0) 현대카드',
    'carriers': ['LG'],
    'issuer': '현대',
    'discount_types': ['할부', '유선청구', '무선청구'],
    'annual_fee': 20000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '',
    'min_installment_amount': None,
    'installment_excluded_items': '청구할인이 적용된 LG통신비\n'
                                  '국세\n'
                                  '공과금\n'
                                  '장기할부(라이트할부) 약정 수납금액\n'
                                  '아파트 관리비\n'
                                  '초/중/고 학교 납입금\n'
                                  '대학/대학원 등록금\n'
                                  '도시가스\n'
                                  '전기요금\n'
                                  '4대 보험 및 장애인 고용부담금\n'
                                  '고속도로 통행요금\n'
                                  '장기카드대출(카드론)\n'
                                  '단기카드대출(현금서비스)\n'
                                  '연회비\n'
                                  '이자 등',
    'contact': '',
    'signup_url': '',
    'extra_benefits': '애플페이 이용 가능\n24개월 이후 M포인트 적립',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [{'threshold': 500000, 'amount': 15000}, {'threshold': 1000000, 'amount': 25000}],
    'benefits_additional': [{'threshold': 500000, 'amount': 17000}, {'threshold': 1000000, 'amount': 9000}],
    'cashback_promo': None},
  { 'name': 'LGU+ x LOCA 롯데카드 (라이트 할부 포함)',
    'carriers': ['LG'],
    'issuer': '롯데',
    'discount_types': ['할부', '유선청구', '무선청구'],
    'annual_fee': 25000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '',
    'min_installment_amount': None,
    'installment_excluded_items': '해당 카드로 할인받은 이용 금액\n'
                                  '국세\n'
                                  '지방세\n'
                                  '도시가스비\n'
                                  '공과금\n'
                                  '4대보험\n'
                                  '초/중/고교 납입금\n'
                                  '대학 등록금\n'
                                  '공공 및 부동산 임대료\n'
                                  '아파트 관리비\n'
                                  '무이자 할부\n'
                                  '단기카드대출\n'
                                  '카드론\n'
                                  '연회비\n'
                                  '이자 및 각종 수수료 등',
    'contact': '1577-3667 / 1588-8100',
    'signup_url': '',
    'extra_benefits': '보상패스 가입 시 1만원 추가 캐시백\n'
                      '롯데백화점 5% 할인\n'
                      '롯데마트/슈퍼 2~3개월 무이자할부\n'
                      '롯데월드 등 주요 놀이공원 50% 할인\n'
                      '롯데시네마 1,500원 할인\n'
                      'SK주유소 리터당 50원 적립',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [ {'threshold': 300000, 'amount': 10000},
                        {'threshold': 500000, 'amount': 15000},
                        {'threshold': 700000, 'amount': 15000},
                        {'threshold': 1000000, 'amount': 20000},
                        {'threshold': 1200000, 'amount': 20000}],
    'benefits_additional': [ {'threshold': 300000, 'amount': 10000},
                             {'threshold': 500000, 'amount': 15000},
                             {'threshold': 700000, 'amount': 9000},
                             {'threshold': 1000000, 'amount': 15000},
                             {'threshold': 1200000, 'amount': 6000}],
    'cashback_promo': { 'title': '갤럭시 S26 시리즈 캐시백',
                        'description': '갤럭시 S26 시리즈 75만원 이상 장기할부 결제 시',
                        'cashback_amount': 100000,
                        'min_installment_amount': 750000,
                        'target_series_ids': [7],
                        'payment_date_text': '',
                        'is_active': True,
                        'sort_order': 0}},
  { 'name': 'LG U+ X 우리카드',
    'carriers': ['LG'],
    'issuer': '우리',
    'discount_types': ['할부', '유선청구', '무선청구'],
    'annual_fee': 25000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '',
    'min_installment_amount': None,
    'installment_excluded_items': '아파트 관리비\n'
                                  'LH/SH임대료\n'
                                  '정부 지원금(보육료, 유치원보조비 등)\n'
                                  '대학(대학원)등록금\n'
                                  '국세\n'
                                  '지방세\n'
                                  '공공요금(공과금)\n'
                                  '단기카드대출\n'
                                  '장기카드대출 등',
    'contact': '',
    'signup_url': '',
    'extra_benefits': '',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [ {'threshold': 400000, 'amount': 10000},
                        {'threshold': 800000, 'amount': 15000},
                        {'threshold': 1200000, 'amount': 20000}],
    'benefits_additional': [ {'threshold': 400000, 'amount': 18000},
                             {'threshold': 800000, 'amount': 14000},
                             {'threshold': 1200000, 'amount': 10000}],
    'cashback_promo': None},
  { 'name': 'U+농협 올원카드',
    'carriers': ['LG'],
    'issuer': 'NH농협',
    'discount_types': ['유선청구', '무선청구'],
    'annual_fee': 15000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '',
    'min_installment_amount': None,
    'installment_excluded_items': '(부분)무이자할부 이용금액\n단기카드대출\n장기카드대출\n국세\n지방세\n공과금(전기/수도)\n아파트 관리비\n초/중/고 학교납입금 전체 등',
    'contact': '1644-2886',
    'signup_url': '',
    'extra_benefits': '추가 할인 18,000원은 캐시백 형태로 제공\n'
                      '스타벅스/이디야 10% 할인\n'
                      '베이커리 10% 할인\n'
                      '영화 CGV 1,000원 할인\n'
                      '주요 놀이공원 50% 할인\n'
                      '전주시 동물원 무료입장',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [{'threshold': 300000, 'amount': 9000}, {'threshold': 500000, 'amount': 15000}],
    'benefits_additional': [{'threshold': 300000, 'amount': 18000}, {'threshold': 700000, 'amount': 33000}],
    'cashback_promo': None},
  { 'name': '스마트 플랜 Plus 신한카드',
    'carriers': ['LG'],
    'issuer': '신한',
    'discount_types': ['할부'],
    'annual_fee': 22000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '',
    'min_installment_amount': None,
    'installment_excluded_items': '현금서비스\n'
                                  '카드론\n'
                                  '연회비\n'
                                  '상품권\n'
                                  '선불전자지급수단 충전\n'
                                  '도시가스/전기요금\n'
                                  '4대보험료\n'
                                  '지방세/국세\n'
                                  '기프트카드\n'
                                  '이자/수수료\n'
                                  '거래취소금액 등',
    'contact': '080-700-3103',
    'signup_url': '',
    'extra_benefits': '',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [{'threshold': 300000, 'amount': 10000}, {'threshold': 700000, 'amount': 15000}],
    'benefits_additional': [{'threshold': 300000, 'amount': 13000}, {'threshold': 700000, 'amount': 10000}],
    'cashback_promo': { 'title': '갤럭시 S26 시리즈 캐시백',
                        'description': '갤럭시 S26 시리즈 장기할부 50만원 이상 결제 시',
                        'cashback_amount': 100000,
                        'min_installment_amount': 500000,
                        'target_series_ids': [7],
                        'payment_date_text': '',
                        'is_active': True,
                        'sort_order': 0}},
  { 'name': 'U+ 라이트할부 II KB국민카드',
    'carriers': ['LG'],
    'issuer': 'KB국민',
    'discount_types': ['할부'],
    'annual_fee': 20000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '',
    'min_installment_amount': None,
    'installment_excluded_items': '(부분)무이자할부\n단기/장기카드대출\n국세\n지방세\n공과금\n아파트관리비\n초/중/고 학교납입금 전체 등',
    'contact': '1577-9900',
    'signup_url': '',
    'extra_benefits': 'KBpay 등록 후 사용 시 3만원 추가, 보상패스 가입 시 3만원 추가 캐시백\n정기결제 이용건수에 따라 월 최대 3,000원 추가 할인',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [ {'threshold': 300000, 'amount': 8000},
                        {'threshold': 700000, 'amount': 12000},
                        {'threshold': 1000000, 'amount': 14000}],
    'benefits_additional': [ {'threshold': 300000, 'amount': 15000},
                             {'threshold': 700000, 'amount': 12000},
                             {'threshold': 1000000, 'amount': 11000}],
    'cashback_promo': { 'title': '갤럭시 S26 시리즈 캐시백',
                        'description': '갤럭시 S26 시리즈 50만원 이상 장기할부 결제 시',
                        'cashback_amount': 80000,
                        'min_installment_amount': 500000,
                        'target_series_ids': [7],
                        'payment_date_text': '',
                        'is_active': True,
                        'sort_order': 0}},
  { 'name': 'LG U+ Bora 신한카드 BigPlus',
    'carriers': ['LG'],
    'issuer': '신한',
    'discount_types': ['할부', '유선청구', '무선청구'],
    'annual_fee': 22000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '',
    'min_installment_amount': None,
    'installment_excluded_items': '장기/단기카드대출\n연회비\n제수수료\n이자\n무이자 할부\n선불카드 구매 및 충전금액\n국세\n지방세\n4대 보험\n거래취소금액 등',
    'contact': '080-850-8853',
    'signup_url': '',
    'extra_benefits': '현대오일뱅크 리터당 40포인트 적립\n영화 온라인 예매 시 1,500원 할인\n롯데월드/서울랜드 50% 할인',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [{'threshold': 300000, 'amount': 10000}, {'threshold': 700000, 'amount': 15000}],
    'benefits_additional': [{'threshold': 400000, 'amount': 23000}, {'threshold': 800000, 'amount': 25000}],
    'cashback_promo': None},
  { 'name': 'U+ Family 하나카드',
    'carriers': ['LG'],
    'issuer': '하나',
    'discount_types': ['할부', '유선청구', '무선청구'],
    'annual_fee': 25000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '통신료 68,000원 이상 자동납부 시 최대 할인 적용',
    'min_installment_amount': None,
    'installment_excluded_items': 'LG U+ 통신비 자동이체 금액\n국세\n지방세\n공과금\n4대보험\n상품권 및 기프트카드 구매\n선불카드 충전\n수도/전기요금\n아파트관리비 등',
    'contact': '1800-1315',
    'signup_url': '',
    'extra_benefits': '',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [{'threshold': 300000, 'amount': 17000}, {'threshold': 700000, 'amount': 25000}],
    'benefits_additional': [{'threshold': 300000, 'amount': 7000}, {'threshold': 700000, 'amount': 0}],
    'cashback_promo': None},
  { 'name': 'LGU+ 더심플 하나카드',
    'carriers': ['LG'],
    'issuer': '하나',
    'discount_types': ['할부', '유선청구', '무선청구'],
    'annual_fee': 25000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': None,
    'add_discount_months': 24,
    'add_discount_condition': '',
    'min_installment_amount': None,
    'installment_excluded_items': '국세\n지방세\n공과금\n수도/전기/도시가스 요금\n아파트 관리비\n사회보험료\n스쿨뱅킹\n초/중/고 학교 납입금 등',
    'contact': '',
    'signup_url': '',
    'extra_benefits': '',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [{'threshold': 300000, 'amount': 10000}, {'threshold': 800000, 'amount': 15000}],
    'benefits_additional': [],
    'cashback_promo': None},
  { 'name': 'LGU+ KB 심플라이트2 카드',
    'carriers': ['LG'],
    'issuer': 'KB국민',
    'discount_types': ['유선청구', '무선청구'],
    'annual_fee': 14000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': None,
    'add_discount_months': 24,
    'add_discount_condition': '',
    'min_installment_amount': None,
    'installment_excluded_items': '해당 카드로 할인받은 이용 건 전체\n'
                                  '단기/장기카드대출\n'
                                  '아파트관리비\n'
                                  '초/중/고 학교납입금\n'
                                  '대학(원)등록금\n'
                                  '정부지원금\n'
                                  '각종 세금/공과금\n'
                                  '4대 사회보험료 등',
    'contact': '1670-8704',
    'signup_url': '',
    'extra_benefits': '',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [{'threshold': 300000, 'amount': 7000}, {'threshold': 700000, 'amount': 11000}],
    'benefits_additional': [],
    'cashback_promo': None},
  { 'name': 'LG U+ 사장님 통할인 신한카드',
    'carriers': ['LG'],
    'issuer': '신한',
    'discount_types': ['유선청구', '무선청구'],
    'annual_fee': 35000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': None,
    'add_discount_months': 24,
    'add_discount_condition': '',
    'min_installment_amount': None,
    'installment_excluded_items': '도시가스/전기요금\n4대보험료\n지방세/국세\n기프트/선불카드 구매\n연회비\n이자\n수수료 등',
    'contact': '080-850-0567',
    'signup_url': '',
    'extra_benefits': '',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [{'threshold': 700000, 'amount': 10000}, {'threshold': 2500000, 'amount': 42000}],
    'benefits_additional': [],
    'cashback_promo': None},
  { 'name': '애플리즘 신한카드',
    'carriers': ['LG'],
    'issuer': '신한',
    'discount_types': ['할부'],
    'annual_fee': 22000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': None,
    'add_discount_months': 24,
    'add_discount_condition': '',
    'min_installment_amount': None,
    'installment_excluded_items': '현금서비스\n카드론\n각종 수수료/이자\n연회비\n거래취소금액\n기프트/선불카드 구매 및 충전\n도시가스/전기요금\n4대보험\n상품권 등',
    'contact': '080-850-8408',
    'signup_url': '',
    'extra_benefits': '',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [{'threshold': 300000, 'amount': 10000}, {'threshold': 700000, 'amount': 15000}],
    'benefits_additional': [],
    'cashback_promo': None},
  { 'name': 'U+ KB국민 체크카드',
    'carriers': ['LG'],
    'issuer': 'KB국민',
    'discount_types': ['무선청구'],
    'annual_fee': 0,
    'signup_start_date': '2026-04-01',
    'signup_end_date': None,
    'add_discount_months': 24,
    'add_discount_condition': '',
    'min_installment_amount': None,
    'installment_excluded_items': '교통비\n무승인금액\n해외이용금액\n대학(원)등록금\n상품권\n선불카드 충전\n포인트리 충전\n지방세\n정부지원금 등',
    'contact': '1588-1688',
    'signup_url': '',
    'extra_benefits': 'CGV 1만원 이상 결제 시 2,000~5,000원 할인\n스타벅스 1만원 이상 결제 시 2,000~5,000원 할인',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [{'threshold': 300000, 'amount': 4000}, {'threshold': 500000, 'amount': 6000}],
    'benefits_additional': [],
    'cashback_promo': None},
  { 'name': 'KT DC Plus 롯데카드',
    'carriers': ['KT'],
    'issuer': '롯데',
    'discount_types': ['유선청구', '무선청구'],
    'annual_fee': 20000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '최초 신규발급(25.10.01 이후 무실적) 후 자동이체 승인 시',
    'min_installment_amount': None,
    'installment_excluded_items': 'KT DC PLUS 롯데카드가 아닌 롯데카드 이용금액\n모든 무이자할부 이용금액\n거래 취소금액\n국세/지방세\n건강보험/국민연금/고용보험/산재보험',
    'contact': '',
    'signup_url': '',
    'extra_benefits': '롯데백화점 5% 할인 쿠폰\n롯데시네마 1,500원 할인\n롯데리아/엔제리너스 1,000원당 50원 할인',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [{'threshold': 400000, 'amount': 10000}, {'threshold': 800000, 'amount': 13000}],
    'benefits_additional': [{'threshold': 400000, 'amount': 14000}, {'threshold': 800000, 'amount': 13000}],
    'cashback_promo': None},
  { 'name': 'KT SUPER DC BC 바로카드',
    'carriers': ['KT'],
    'issuer': 'BC',
    'discount_types': ['할부', '유선청구', '무선청구'],
    'annual_fee': 25000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '최초 자동이체 등록 및 단일 통신비 2.7만원 이상 매출 발생 시\n[Mastercard 기준]',
    'min_installment_amount': None,
    'installment_excluded_items': '아파트 관리비\n무이자 할부 이용 금액\n단기카드대출\n장기카드대출\n연회비\n연체료\n각종 수수료/이자',
    'contact': '',
    'signup_url': '',
    'extra_benefits': '',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [ {'threshold': 400000, 'amount': 5000},
                        {'threshold': 800000, 'amount': 7000},
                        {'threshold': 1200000, 'amount': 9000}],
    'benefits_additional': [ {'threshold': 400000, 'amount': 20000},
                             {'threshold': 800000, 'amount': 19000},
                             {'threshold': 1200000, 'amount': 18000}],
    'cashback_promo': None},
  { 'name': '슈퍼 2.0+M Edition3 통신할인형 2.0 (현대카드)',
    'carriers': ['KT'],
    'issuer': '현대',
    'discount_types': ['할부', '유선청구', '무선청구'],
    'annual_fee': 20000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '최초 신규 발급(25.10.01 이후 무실적) 후 자동이체 등록 시',
    'min_installment_amount': None,
    'installment_excluded_items': '청구할인이 적용된 KT통신비\n'
                                  '국세/공과금\n'
                                  '장기할부(라이트할부) 약정 수납금액\n'
                                  '아파트 관리비\n'
                                  '초/중/고 학교 납입금\n'
                                  '대학/원 등록금\n'
                                  '도시가스/전기요금\n'
                                  '4대보험',
    'contact': '',
    'signup_url': '',
    'extra_benefits': '애플페이 가능\nM포인트 사용처: GS칼텍스, 아웃백, 현대·기아차 서비스센터 등',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [{'threshold': 500000, 'amount': 15000}, {'threshold': 1000000, 'amount': 25000}],
    'benefits_additional': [{'threshold': 500000, 'amount': 17000}, {'threshold': 1000000, 'amount': 9000}],
    'cashback_promo': None},
  { 'name': 'KT DC Plus BC 바로카드',
    'carriers': ['KT'],
    'issuer': 'BC',
    'discount_types': ['유선청구', '무선청구'],
    'annual_fee': 12000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '신규/교체/추가 발급 후 자동이체 등록 시(단일 통신비 2만원 이상)\n[Mastercard 기준]',
    'min_installment_amount': None,
    'installment_excluded_items': '아파트 관리비\n단기카드대출\n장기카드대출\n연회비\n제세공과금\n4대 보험',
    'contact': '',
    'signup_url': '',
    'extra_benefits': 'Mastercard Platinum 등급 기본 서비스 제공\nSK주유소 1% 청구할인',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [{'threshold': 300000, 'amount': 7000}, {'threshold': 700000, 'amount': 13000}],
    'benefits_additional': [{'threshold': 300000, 'amount': 8000}, {'threshold': 700000, 'amount': 5000}],
    'cashback_promo': None},
  { 'name': 'KT Plus 우리카드',
    'carriers': ['KT'],
    'issuer': '우리',
    'discount_types': ['할부', '유선청구', '무선청구'],
    'annual_fee': 25000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '직전 6개월 무실적 고객이 카드 발급 후 자동이체 승인 시',
    'min_installment_amount': None,
    'installment_excluded_items': '아파트관리비\nLH/SH임대료\n정부지원금\n대학 등록금\n국세/지방세\n공공요금\n단기/장기카드대출',
    'contact': '',
    'signup_url': '',
    'extra_benefits': '',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [ {'threshold': 400000, 'amount': 10000},
                        {'threshold': 800000, 'amount': 15000},
                        {'threshold': 1200000, 'amount': 20000}],
    'benefits_additional': [ {'threshold': 400000, 'amount': 18000},
                             {'threshold': 800000, 'amount': 14000},
                             {'threshold': 1200000, 'amount': 10000}],
    'cashback_promo': None},
  { 'name': 'KT 36 Plus 우리카드',
    'carriers': ['KT'],
    'issuer': '우리',
    'discount_types': ['할부', '유선청구', '무선청구'],
    'annual_fee': 25000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '직전 6개월 무실적 고객이 장기할부(36개월) 결제 완료 시',
    'min_installment_amount': None,
    'installment_excluded_items': '아파트 관리비\n무이자 할부 이용 금액\n단기카드대출\n장기카드대출\n연회비\n연체료\n각종 수수료/이자',
    'contact': '',
    'signup_url': '',
    'extra_benefits': '',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [ {'threshold': 400000, 'amount': 8000},
                        {'threshold': 800000, 'amount': 13000},
                        {'threshold': 1200000, 'amount': 18000}],
    'benefits_additional': [ {'threshold': 400000, 'amount': 13000},
                             {'threshold': 800000, 'amount': 13000},
                             {'threshold': 1200000, 'amount': 10000}],
    'cashback_promo': None},
  { 'name': 'KT 가족만족 DC 신한카드',
    'carriers': ['KT'],
    'issuer': '신한',
    'discount_types': ['유선청구', '무선청구'],
    'annual_fee': 15000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '직전 6개월 무실적 고객이 통신비 자동이체 등록 시',
    'min_installment_amount': None,
    'installment_excluded_items': '단기카드대출\n장기카드대출\n연회비\n수수료\n도시가스/전기요금\n4대보험',
    'contact': '',
    'signup_url': '',
    'extra_benefits': '가족카드 발급 시 36개월간 월 3,000원 추가 캐시백\n'
                      '현대오일뱅크 주유 리터당 40포인트 적립\n'
                      '롯데월드/서울랜드 50% 할인\n'
                      '영화 온라인 예매 시 1,500원 할인',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [{'threshold': 300000, 'amount': 7000}, {'threshold': 700000, 'amount': 15000}],
    'benefits_additional': [{'threshold': 300000, 'amount': 13000}, {'threshold': 700000, 'amount': 10000}],
    'cashback_promo': None},
  { 'name': 'KT 으랏차차 신한카드',
    'carriers': ['KT'],
    'issuer': '신한',
    'discount_types': ['유선청구', '무선청구'],
    'annual_fee': 36000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': 'Master 카드로 최초 신규 발급 및 자동이체 등록 시',
    'min_installment_amount': None,
    'installment_excluded_items': '기프트카드/선불카드 구매 및 충전\n국세/지방세\n4대 보험\n대학 등록금\n아파트 관리비\n도시가스/전기요금/TV수신료',
    'contact': '',
    'signup_url': '',
    'extra_benefits': '통신비 고액 할인 및 신한은행 계좌 연결 시 매월 추가 입금',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [{'threshold': 500000, 'amount': 12000}, {'threshold': 2000000, 'amount': 33000}],
    'benefits_additional': [{'threshold': 500000, 'amount': 10000}, {'threshold': 2000000, 'amount': 12000}],
    'cashback_promo': None},
  { 'name': 'KT 삼성카드',
    'carriers': ['KT'],
    'issuer': '삼성',
    'discount_types': ['할부', '유선청구', '무선청구'],
    'annual_fee': 20000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '최초 신규발급 후 26.05.31까지 정기결제 납부 시',
    'min_installment_amount': None,
    'installment_excluded_items': '현금서비스\n'
                                  '카드론\n'
                                  '각종 수수료 및 이자\n'
                                  '연회비\n'
                                  '연체료\n'
                                  '대중교통\n'
                                  '택시\n'
                                  '아파트 관리비\n'
                                  '부동산 임대료\n'
                                  '상품권 구매\n'
                                  '4대보험료\n'
                                  '지방세/국세',
    'contact': '',
    'signup_url': '',
    'extra_benefits': '자동이체 항목 추가 시 건당 1,000원 추가 할인(최대 3,000원)',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [ {'threshold': 300000, 'amount': 7000},
                        {'threshold': 700000, 'amount': 10000},
                        {'threshold': 1200000, 'amount': 13000}],
    'benefits_additional': [ {'threshold': 300000, 'amount': 13000},
                             {'threshold': 700000, 'amount': 11000},
                             {'threshold': 1200000, 'amount': 9000}],
    'cashback_promo': None},
  { 'name': 'KT 할부 Plus NH 농협카드',
    'carriers': ['KT'],
    'issuer': 'NH농협',
    'discount_types': ['할부', '무선청구'],
    'annual_fee': 20000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '최초 발급 후 자동이체 또는 슈퍼할부(최소 10만원) 등록 시',
    'min_installment_amount': None,
    'installment_excluded_items': '대학 등록금\n각종 세금 및 공과금\n상하수도 요금\n과태료\n사회보험\n아파트 관리비',
    'contact': '',
    'signup_url': '',
    'extra_benefits': '스타벅스/이디야 10% 할인\n파리바게뜨/배스킨라빈스 10% 할인\nVISA 플래티넘 공항 라운지 이용',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [{'threshold': 400000, 'amount': 5000}, {'threshold': 800000, 'amount': 10000}],
    'benefits_additional': [ {'threshold': 400000, 'amount': 18000},
                             {'threshold': 800000, 'amount': 18000},
                             {'threshold': 1200000, 'amount': 33000}],
    'cashback_promo': None},
  { 'name': 'KT 할부 S 삼성 카드',
    'carriers': ['KT'],
    'issuer': '삼성',
    'discount_types': ['할부'],
    'annual_fee': 25000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '',
    'min_installment_amount': None,
    'installment_excluded_items': '무이자 할부 이용금액\n아파트 관리비\n단기/장기카드대출\n연회비\n제세공과금',
    'contact': '',
    'signup_url': '',
    'extra_benefits': '',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [ {'threshold': 400000, 'amount': 10000},
                        {'threshold': 800000, 'amount': 15000},
                        {'threshold': 1200000, 'amount': 20000}],
    'benefits_additional': [ {'threshold': 400000, 'amount': 12000},
                             {'threshold': 800000, 'amount': 8000},
                             {'threshold': 1200000, 'amount': 4000}],
    'cashback_promo': { 'title': '갤럭시 S26 시리즈 캐시백',
                        'description': '갤럭시 S26 시리즈 슈퍼할부 30만원 이상 결제 + 자동납부 연결 시',
                        'cashback_amount': 100000,
                        'min_installment_amount': 300000,
                        'target_series_ids': [7],
                        'payment_date_text': '2026-05-20 이후',
                        'is_active': True,
                        'sort_order': 0}},
  { 'name': 'KT DC Plus 고객용 더 심플 하나카드',
    'carriers': ['KT'],
    'issuer': '하나',
    'discount_types': ['유선청구', '무선청구'],
    'annual_fee': 25000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': None,
    'add_discount_months': 24,
    'add_discount_condition': '',
    'min_installment_amount': None,
    'installment_excluded_items': '국세/지방세\n공과금\n수도/전기/도시가스 요금\n아파트 관리비\n사회보험료 납부 금액 등',
    'contact': '1800-1111',
    'signup_url': '',
    'extra_benefits': '',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [{'threshold': 300000, 'amount': 10000}, {'threshold': 800000, 'amount': 15000}],
    'benefits_additional': [],
    'cashback_promo': None},
  { 'name': 'K BANK 더블혜택 체크카드',
    'carriers': ['KT'],
    'issuer': 'K뱅크',
    'discount_types': ['무선청구'],
    'annual_fee': 0,
    'signup_start_date': '2026-04-01',
    'signup_end_date': None,
    'add_discount_months': 24,
    'add_discount_condition': '전월실적 조건 충족 및 통신요금 자동이체 시 캐시백',
    'min_installment_amount': None,
    'installment_excluded_items': '등록금\n관리비\n상품권\n기프트카드\n제세공과금\n교통비 등',
    'contact': '',
    'signup_url': '',
    'extra_benefits': '',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [ {'threshold': 200000, 'amount': 5000},
                        {'threshold': 500000, 'amount': 10000},
                        {'threshold': 1000000, 'amount': 20000}],
    'benefits_additional': [],
    'cashback_promo': None},
  { 'name': 'KT 신한 체크카드',
    'carriers': ['KT'],
    'issuer': '신한',
    'discount_types': ['무선청구'],
    'annual_fee': 0,
    'signup_start_date': '2026-04-01',
    'signup_end_date': None,
    'add_discount_months': 24,
    'add_discount_condition': '',
    'min_installment_amount': None,
    'installment_excluded_items': '수수료/이자\n기프트카드/선불카드 충전\n거래취소금액 등',
    'contact': '',
    'signup_url': '',
    'extra_benefits': 'GS25 5% 캐시백\nCGV 10% 캐시백',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [{'threshold': 300000, 'amount': 3000}, {'threshold': 500000, 'amount': 5000}],
    'benefits_additional': [],
    'cashback_promo': None},
  { 'name': 'KT 가족만족 할부 신한카드',
    'carriers': ['KT'],
    'issuer': '신한',
    'discount_types': ['할부'],
    'annual_fee': 22000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '',
    'min_installment_amount': None,
    'installment_excluded_items': '현금서비스\n카드론\n연회비\n도시가스/전기요금\n4대보험',
    'contact': '',
    'signup_url': '',
    'extra_benefits': '',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [{'threshold': 300000, 'amount': 10000}, {'threshold': 700000, 'amount': 15000}],
    'benefits_additional': [{'threshold': 300000, 'amount': 13000}, {'threshold': 700000, 'amount': 10000}],
    'cashback_promo': { 'title': '갤럭시 S26 시리즈 캐시백',
                        'description': '갤럭시 S26 시리즈 슈퍼할부 50만원 이상 결제 시',
                        'cashback_amount': 100000,
                        'min_installment_amount': 500000,
                        'target_series_ids': [7],
                        'payment_date_text': '',
                        'is_active': True,
                        'sort_order': 0}},
  { 'name': 'KT 할부 Plus KB국민카드',
    'carriers': ['KT'],
    'issuer': 'KB국민',
    'discount_types': ['할부'],
    'annual_fee': 20000,
    'signup_start_date': '2026-04-01',
    'signup_end_date': '2026-04-30',
    'add_discount_months': 24,
    'add_discount_condition': '',
    'min_installment_amount': None,
    'installment_excluded_items': 'KT 통신요금(유/무선)\n무이자 할부\n아파트 관리비\n국세/지방세/공과금\n4대 사회보험료',
    'contact': '',
    'signup_url': '',
    'extra_benefits': 'KBpay 등록 후 사용 시 3만원 추가 캐시백',
    'is_active': True,
    'sort_order': 0,
    'benefits_basic': [ {'threshold': 300000, 'amount': 8000},
                        {'threshold': 700000, 'amount': 12000},
                        {'threshold': 1000000, 'amount': 14000}],
    'benefits_additional': [ {'threshold': 300000, 'amount': 15000},
                             {'threshold': 700000, 'amount': 12000},
                             {'threshold': 1000000, 'amount': 11000}],
    'cashback_promo': { 'title': '갤럭시 S26 시리즈 캐시백',
                        'description': '갤럭시 S26 시리즈 슈퍼할부 50만원 이상 결제 시',
                        'cashback_amount': 80000,
                        'min_installment_amount': 500000,
                        'target_series_ids': [7],
                        'payment_date_text': '',
                        'is_active': True,
                        'sort_order': 0}}]
