# Generated by Django 5.2.5 on 2025-12-26 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraps.device')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraps.carrier')),
            ],
        ),
        migrations.CreateModel(
            name='PriceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=100)),
                ('contract_type', models.CharField(max_length=50)),
                ('discount_type', models.CharField(max_length=50)),
                ('subsidy_common', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subsidy_add', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subsidy_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraps.company')),
                ('device_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraps.devicevariant')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraps.plan')),
            ],
        ),
    ]
