# Generated by Django 5.2.5 on 2026-04-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricelog",
            name="contract_type",
            field=models.CharField(
                choices=[
                    ("신규", "신규"),
                    ("번호이동", "번호이동"),
                    ("기기변경", "기기변경"),
                ],
                default="번호이동",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="pricelog",
            name="discount_type",
            field=models.CharField(
                choices=[("공시지원금", "공시지원금"), ("선택약정", "선택약정")],
                default="공시지원금",
                max_length=50,
            ),
        ),
    ]
