# Generated by Django 5.2.5 on 2025-11-14 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('internet', '0001_initial'), ('internet', '0002_installationoption'), ('internet', '0003_tvplan_tv_contract_discount_and_more'), ('internet', '0004_remove_bundlediscount_carrier')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BundleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internet_price_min', models.IntegerField(default=0)),
                ('tv_price_min', models.IntegerField(default=0)),
                ('mobile_price_min', models.IntegerField(default=0)),
                ('mobile_type', models.CharField(blank=True, choices=[('MNO', 'MNO'), ('MVNO', 'MVNO'), ('None', 'None')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternetCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='carrier_logos/')),
                ('wifi_router_rental_price_per_month', models.IntegerField(default=0)),
                ('tv_settop_box_rental_price_per_month', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BundlePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_amount', models.IntegerField(default=0)),
                ('cash_amount', models.IntegerField(default=0)),
                ('bundle_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_promotions', to='internet.bundlecondition')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_promotions', to='internet.internetcarrier')),
            ],
        ),
        migrations.AddField(
            model_name='bundlecondition',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_conditions', to='internet.internetcarrier'),
        ),
        migrations.CreateModel(
            name='InternetPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('speed', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('internet_price_per_month', models.IntegerField(default=0)),
                ('internet_contract_discount', models.IntegerField(default=0)),
                ('is_wifi_router_free', models.BooleanField(default=False)),
                ('is_wifi_router_selectable', models.BooleanField(default=False)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internet_plans', to='internet.internetcarrier')),
            ],
        ),
        migrations.CreateModel(
            name='InstallationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_type', models.CharField(choices=[('I', 'Internet'), ('IT', 'Internet + TV'), ('AT', 'Additional TV')], max_length=2)),
                ('installation_fee', models.IntegerField(default=0)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_options', to='internet.internetcarrier')),
            ],
        ),
        migrations.CreateModel(
            name='TVPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('channel_count', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_settop_box_free', models.BooleanField(default=False)),
                ('is_settop_box_selectable', models.BooleanField(default=False)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tv_plans', to='internet.internetcarrier')),
                ('tv_contract_discount', models.IntegerField(default=0)),
                ('tv_price_per_month', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BundleDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_name', models.CharField(max_length=100)),
                ('discount_type', models.CharField(choices=[('Mobile', 'Mobile'), ('Internet', 'Internet'), ('TV', 'TV')], max_length=100)),
                ('discount_amount', models.IntegerField(default=0)),
                ('bundle_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_discounts', to='internet.bundlecondition')),
            ],
        ),
    ]
