# Generated by Django 5.2.5 on 2025-11-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0001_initial_squashed_0004_remove_bundlediscount_carrier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundlepromotion',
            name='carrier',
        ),
    ]
