# Generated by Django 5.2.5 on 2025-11-17 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0005_remove_bundlepromotion_carrier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundlecondition',
            name='internet_price_min',
        ),
        migrations.RemoveField(
            model_name='bundlecondition',
            name='tv_price_min',
        ),
        migrations.AddField(
            model_name='bundlecondition',
            name='internet_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_conditions', to='internet.internetplan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bundlecondition',
            name='tv_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_conditions', to='internet.tvplan'),
            preserve_default=False,
        ),
    ]
