# Generated by Django 5.2.5 on 2025-11-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0006_remove_bundlecondition_internet_price_min_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedDataView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '종합 리포트',
                'verbose_name_plural': '종합 리포트',
                'managed': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='bundlecondition',
            unique_together={('carrier', 'internet_plan', 'tv_plan', 'mobile_type')},
        ),
    ]
