# Generated by Django 5.2.5 on 2025-11-20 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internet", "0007_combineddataview_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bundlecondition",
            name="tv_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bundle_conditions",
                to="internet.tvplan",
            ),
        ),
    ]
