# Generated by Django 5.2.5 on 2025-11-27 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internet", "0008_alter_bundlecondition_tv_plan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="internetcarrier",
            name="tv_settop_box_rental_price_per_month",
        ),
        migrations.RemoveField(
            model_name="internetcarrier",
            name="wifi_router_rental_price_per_month",
        ),
        migrations.RemoveField(
            model_name="internetplan",
            name="is_wifi_router_free",
        ),
        migrations.RemoveField(
            model_name="internetplan",
            name="is_wifi_router_selectable",
        ),
        migrations.RemoveField(
            model_name="tvplan",
            name="is_settop_box_free",
        ),
        migrations.RemoveField(
            model_name="tvplan",
            name="is_settop_box_selectable",
        ),
        migrations.AlterField(
            model_name="bundlediscount",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("Mobile", "Mobile"),
                    ("Internet", "Internet"),
                    ("TV", "TV"),
                    ("Internet_Install", "Internet Install"),
                    ("TV_Install", "TV Install"),
                    ("Wifi", "Wifi"),
                    ("TV_Settop", "TV Settop"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="installationoption",
            name="installation_type",
            field=models.CharField(
                choices=[
                    ("I", "Internet"),
                    ("T", "TV"),
                    ("AI", "Additional Internet"),
                    ("AT", "Additional TV"),
                ],
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="SettopBoxOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("rental_price_per_month", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "carrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settop_box_options",
                        to="internet.internetcarrier",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bundlecondition",
            name="settop_box_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bundle_conditions",
                to="internet.settopboxoption",
            ),
        ),
        migrations.CreateModel(
            name="WifiOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("rental_price_per_month", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "carrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wifi_options",
                        to="internet.internetcarrier",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bundlecondition",
            name="wifi_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bundle_conditions",
                to="internet.wifioption",
            ),
        ),
    ]
