# Generated by Django 5.2.5 on 2025-11-28 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0009_remove_internetcarrier_tv_settop_box_rental_price_per_month_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bundlecondition',
            unique_together={('carrier', 'internet_plan', 'tv_plan', 'mobile_type', 'wifi_option', 'settop_box_option')},
        ),
    ]
