# Generated by Django 5.2.5 on 2025-11-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0010_alter_bundlecondition_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundlecondition',
            name='mobile_type',
            field=models.CharField(blank=True, choices=[('MNO', 'MNO'), ('MVNO', 'MVNO')], max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bundlediscount',
            unique_together={('bundle_condition', 'bundle_name', 'discount_type')},
        ),
    ]
