# Generated by Django 5.2.5 on 2025-12-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0011_alter_bundlecondition_mobile_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetplan',
            name='isWifiIncluded',
            field=models.BooleanField(default=False),
        ),
    ]
