# Generated by Django 5.2.5 on 2025-12-04 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0012_internetplan_iswifiincluded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('주문접수', '주문접수'), ('해피콜진행중', '해피콜진행중'), ('해피콜완료', '해피콜완료'), ('설치요청', '설치요청'), ('설치중', '설치중'), ('배송완료', '배송완료'), ('개통대기', '개통대기'), ('개통완료', '개통완료'), ('사은품지급완료', '사은품지급완료'), ('취소요청', '취소요청'), ('취소완료', '취소완료')], default='주문접수', max_length=50)),
                ('bundle_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='internet.bundlecondition')),
            ],
        ),
    ]
