steps:
  - uses: actions/checkout@v2
  - uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  - uses: sparkplug-app/install-eb-cli-action
  - run: eb init pio
  - run: eb deploy prod-7
